

version: "3"


services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fast_tinyurl
    container_name: app
    volumes:
      - ./app:/app/
    ports:
      - "8888:80"
    env_file:
      - .env.docker
    environment:
      DEBUG: "True"


  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
